/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.ms;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author PRANAV K A
 */
public class Home extends javax.swing.JFrame {

    public String email;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String userEmail) {
        initComponents();
        email = userEmail;
        if (!email.equals("admin@gmail.com")) {
            btnCategory.setVisible(false);
            btnNewproduct.setVisible(false);
            btnEditproduct.setVisible(false);
            btnVerify.setVisible(false);
            rightbackoption.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        btnChangepswrd = new javax.swing.JButton();
        btnbill = new javax.swing.JButton();
        ChangeSecurityQuestion = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnNewproduct = new javax.swing.JButton();
        btnEditproduct = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rightbackoption = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/left-arrow (1).png"))); // NOI18N
        btnLogin.setText("Logout");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        btnPlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newicons/add (1).png"))); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 240, -1));

        btnChangepswrd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangepswrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newicons/reset-password (1).png"))); // NOI18N
        btnChangepswrd.setText("Change Password");
        btnChangepswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangepswrdActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangepswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 240, -1));

        btnbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newicons/invoice.png"))); // NOI18N
        btnbill.setText("View bill & Placed Details");
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });
        getContentPane().add(btnbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 240, -1));

        ChangeSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChangeSecurityQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newicons/question (1).png"))); // NOI18N
        ChangeSecurityQuestion.setText("Change Security Question");
        ChangeSecurityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSecurityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(ChangeSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 240, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, -1, -1));

        btnCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newicons/list (1).png"))); // NOI18N
        btnCategory.setText("Manage Category");
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 220, 220, -1));

        btnNewproduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNewproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newicons/box (1).png"))); // NOI18N
        btnNewproduct.setText("New Product");
        btnNewproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, 220, 40));

        btnEditproduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newicons/info (1).png"))); // NOI18N
        btnEditproduct.setText("View & Edit  Product");
        btnEditproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 360, 220, 40));

        btnVerify.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newicons/user (1).png"))); // NOI18N
        btnVerify.setText("Verify Users");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 430, 220, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/board1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 100, 530, 640));

        rightbackoption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/board1.png"))); // NOI18N
        getContentPane().add(rightbackoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 580, 630));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homescreenbig2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close the Application", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
        
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnNewproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewproductActionPerformed
        // TODO add your handling code here:
        new AddNewProduct().setVisible(true);
        
    }//GEN-LAST:event_btnNewproductActionPerformed

    private void btnEditproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditproductActionPerformed
        // TODO add your handling code here:
        new ViewEditDeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnEditproductActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
        new VerifyUsers().setVisible(true);
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PlaceOrder(email).setVisible(true);
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
        // TODO add your handling code here:
        new ViewBillsOrderPlacedDetails().setVisible(true);
        
    }//GEN-LAST:event_btnbillActionPerformed

    private void btnChangepswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangepswrdActionPerformed
        // TODO add your handling code here:
        if(email.equals("admin@gmail.com")){
        new ChangePassword(email).setVisible(true);}
        else {
             new ChangePassword1(email).setVisible(true);
        }
    }//GEN-LAST:event_btnChangepswrdActionPerformed

    private void ChangeSecurityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSecurityQuestionActionPerformed
        // TODO add your handling code here:
      if(email.equals("admin@gmail.com")){
        new ChangeSecurityQuestion(email).setVisible(true);}
        else {
             new ChangeSecurityQuestion1(email).setVisible(true);
        }
    }//GEN-LAST:event_ChangeSecurityQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                } UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeSecurityQuestion;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnChangepswrd;
    private javax.swing.JButton btnEditproduct;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewproduct;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnVerify;
    private javax.swing.JButton btnbill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel rightbackoption;
    // End of variables declaration//GEN-END:variables
}
